version: "3"

services:

  gdx-mail-server: 
    image: "ramesesinc/mail-server:latest"
    container_name: gdx-mail-server
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ./env.conf
      - ../_custom/env.conf
    ports:
      - "25:25"
